// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZ22l1u7usFZty7pEOHCDTmpa7jtlMSA',
    appId: '1:104959127186:android:e03332c7cff1fcbbe0804b',
    messagingSenderId: '104959127186',
    projectId: 'aid-delivery-system',
    storageBucket: 'aid-delivery-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCICNnfCj5SUUT-mPeFjiKGwFjjbPH-9b0',
    appId: '1:104959127186:ios:7e5d627a6b801d00e0804b',
    messagingSenderId: '104959127186',
    projectId: 'aid-delivery-system',
    storageBucket: 'aid-delivery-system.firebasestorage.app',
    iosBundleId: 'app.mosd.gov.ps.mosdFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgNbmbkhGEZl7kTAGanejxyT2pSia8qD0',
    appId: '1:104959127186:web:a667fa7d2ef2c2d5e0804b',
    messagingSenderId: '104959127186',
    projectId: 'aid-delivery-system',
    authDomain: 'aid-delivery-system.firebaseapp.com',
    storageBucket: 'aid-delivery-system.firebasestorage.app',
    measurementId: 'G-B0WNF36M7D',
  );

}